services:
  ui:
    image: node:24-alpine
    working_dir: /app
    command: sh -c "npm run dev -- --host 0.0.0.0"
    ports:
      - "3000:3000"
    volumes:
      - ./src/ui:/app

  # mongodb:
  #   image: mongo:8.3.7-noble
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - /data/db

  rabbitmq:
    image: rabbitmq:4.3.4-alpine
    ports:
      - "5672:5672"
      - "5671:5671"
    volumes:
      - /var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq-enabled-plugins:/etc/rabbitmq/enabled_plugins:ro
      - ./certs:/certs:ro
    depends_on:
      - dex
      - caddy

  dex:
    image: dexidp/dex:v2.45.1-alpine
    command: ["dex", "serve", "/etc/dex/config.yml"]
    volumes:
      - ./dex-config.yml:/etc/dex/config.yml:ro

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./certs:/certs:ro
    networks:
      default:
        aliases:
          - dex.localhost
    depends_on:
      - dex
