auth_backends.1 = oauth2

auth_oauth2.resource_server_id = rabbitmq
auth_oauth2.issuer = https://dex.localhost/dex
auth_oauth2.jwks_url = https://dex.localhost/dex/keys
auth_oauth2.https.cacertfile = /certs/rootCA.pem

listeners.ssl.default = 5671
ssl_options.certfile = /certs/rabbitmq.localhost.pem
ssl_options.keyfile = /certs/rabbitmq.localhost-key.pem
ssl_options.verify = verify_none
ssl_options.fail_if_no_peer_cert = false
