auth_backends.1 = oauth2

auth_oauth2.resource_server_id = rabbitmq
auth_oauth2.issuer = https://dex.localhost
auth_oauth2.jwks_uri = https://dex.localhost/keys
auth_oauth2.https.cacertfile = /certs/rootCA.pem
auth_oauth2.additional_scopes_key = aud
auth_oauth2.preferred_username_claims.1 = email
auth_oauth2.scope_aliases.rabbitmq = rabbitmq.configure:*/mqtt-subscription-{email}qos* rabbitmq.write:*/mqtt-subscription-{email}qos* rabbitmq.read:*/mqtt-subscription-{email}qos* rabbitmq.write:*/amq.topic rabbitmq.read:*/amq.topic rabbitmq.write:*/amq.topic/{email}.* rabbitmq.read:*/amq.topic/{email}.*

management.load_definitions = /etc/rabbitmq/definitions.json

listeners.ssl.default = 5671
ssl_options.certfile = /certs/rabbitmq.localhost.pem
ssl_options.keyfile = /certs/rabbitmq.localhost-key.pem
ssl_options.verify = verify_none
ssl_options.fail_if_no_peer_cert = false
